#!/usr/bin/env bash
#This script Does the following:
#  Create a file /var/run/myscript.pid containing the script PID.
#  Displays "To infinity and beyond" indefinitely
#  Displays "I hate the kill command" upon receiving a SIGTERM
#  Displays "Y U no love me?!" upon receiving a SIGINT
#  Deletes the file /var/run/mycript.pid and terminates 
#  

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command" && terminator' SIGTERM
trap 'terminator' SIGQUIT

while true
do
  echo "To infinity and beyond"
  sleep 2
done
