#!/usr/bin/env bash

# Displays after Looping from 1 to 10:
#         Displays "bad luck" for the 4th iteration
#         Displays good luck" for the 8th iterations
#         Best School" for all other iterations

count=0

while [ $count -lt 10 ]
do    
     if [ $count -eq 3 ]
     then
          echo "bad luck"
     elif [ $count -eq 7 ]
     then
           echo "good luck"
     else
           echo "Best School"
     fi
     (( count++ ))
done
