#!/usr/bin/env bash

# Connect to the server using ssh with the specified private key and user
ssh -i ~/.ssh/school ubuntu@52.91.151.94

# Connects to server 100.25.167.76 with key in ~/.ssh/school

ssh -i ~/.ssh/school ubuntu@100.25.167.76

